# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20170823_0503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_update_authors', 'Can manipulate authors table'), ('can_get_authors', 'Can get authors list'))},
        ),
    ]
